---
name: Qualify Code

permissions:
  contents: read

"on":
  push:
  pull_request:
  workflow_dispatch:

jobs:
  call-common-uv-qualify:
    uses: Seika139/.github/.github/workflows/uv-qualify.yml@main
    with:
      python-version: "3.13"
    secrets: inherit
